### PR TITLE
feat: add conditional link to sidebar logo

### PR DESCRIPTION
**Pull request by rlafuente**
This one is straightforward; only question is whether the hardcoded URLs are okay to use?

### CODE REVIEW

**Comment by wpf500** [comment]
You should use a `<router-link>` component to use the internal Vue router, and link to `/` as that *should* redirect to the right place based on if the user is an admin or not.

```vue
<router-link to="/">
...
</router-link>
```

**Comment by rlafuente** [comment]
oh right -- fixed!

**Comment by wpf500** [comment]
Thanks. Can you also remove the unused import `canAdmin`?

**Comment by rlafuente** [comment]
d'oh, fixed

**Pull request merged**
