### PR TITLE
Basic admin dashboard

### PR DESCRIPTION
**Pull request by wpf500**
A basic admin dashboard

image

To do:
- [x] Hook up to API
- [x] Add background to Slack prompt
- [x] Get text for hints
- [x] Add more to `CalloutSummary`

### CODE REVIEW

**Review by basilesimon — APPROVED** [review]
We'll have a bit of localisation to do, inc. on the key stats, but otherwise 👌

**Comment by basilesimon** [comment]
@wpf500 I know it's silly, but could you tweak the database so that the latest callout is one with an `excerpt` and an `image`?

**Comment by basilesimon** [comment]
image

Just for reference, this is the callout summary as per the spec.

**Comment by basilesimon** [comment]
@beabee-communityrm/design: 

https://github.com/beabee-communityrm/beabee-frontend/pull/153/commits/d6eb218aaa31ef182937caaa36712e2fb53f24bd adds the background image for the "join our slack" section. You can replace the PNG with a high-res or more compressed version if you wish.

I also went rogue and added a glowing white text-shadow to improve legibility on small viewports. Please review and tweak as you see fit 👌

**Comment by rlafuente** [comment]
Possible alternatives for the copy in hint boxes\* 

- Did you know callouts can be created without an end date, and just keep running? See our [feature showcase](https://beabee.io/en/beabee-full-feature-list/) for more.
- Find out more about [the Beabee vision](https://beabee.io/en/beabee-model/) around community engagement and meaningful relationships with your audience.
- Our [FAQ](https://beabee.io/en/beabee-faq/) addresses common questions about getting started and use cases. If the answer you're looking for isn't there, get in touch.

\* we should settle on a stable name for those

**Comment by basilesimon** [comment]
Big love to [this great commit](https://github.com/beabee-communityrm/beabee-frontend/pull/153/commits/43c2b06f37e324a1a0bbf170ac4eb71f669bdf2e): https://github.com/beabee-communityrm/beabee-frontend/pull/153/commits/43c2b06f37e324a1a0bbf170ac4eb71f669bdf2e

**Pull request merged**
