### PR TITLE
feat: use generalContent values for footer links

### PR DESCRIPTION
**Pull request by rlafuente**

### CODE REVIEW

**Comment by basilesimon** [comment]
👍 That's good enough for the type checker and for me :)

**Review by basilesimon — APPROVED** [review]

**Review by wpf500 — CHANGES_REQUESTED** [review]
Looks good. A couple of changes:
* `termsLink` is optional, sorry this wasn't in the spec. Can you just add a `v-if` for it
* Can you remove the unused i18n keys from the spreadsheet and update the locales

**Comment by wpf500** [comment]
Oh I've also just seen that "Contact us at" isn't internationalised, could you add it?

**Comment by rlafuente** [comment]
Updated, please check!

**Review by wpf500 — APPROVED** [review]

**Pull request merged**
